config/routes.rb
Shurijp::Application.routes.draw do

  resources :vmresavation, only: [:new, :create, :edit, :update, :destroy]
  match 'vmresavation/:id', :to => 'vmresavation#index', :as => 'vmresavation', :via => :get

  resources :resavations, only: [:index, :show]

  get "user_property/index"

  resources :providers

  root :to => "conns#index"

  devise_for :users
  get 'conns', :to => 'conns#index', :as => :user_root

  resources :conns
  resources :vm_operations, only: [ :new, :create ] do
    member do
      get :start, :stop, :reboot
    end
  end

  match 'vm_operations/:idx', :to => 'vm_operations#index', :as => 'vm_operations', :via => :get

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :conns
  attr_accessible :name, :create_vm, :start_vm, :stop_vm, :reboot_vm, :list_vm
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_login

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @providers }
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @provider = Provider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/new
  # GET /providers/new.json
  def new
    @provider = Provider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/1/edit
  def edit
    @provider = Provider.find(params[:id])
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(params[:provider])

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render json: @provider, status: :created, location: @provider }
      else
        format.html { render action: "new" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /providers/1
  # PUT /providers/1.json
  def update
    @provider = Provider.find(params[:id])

    respond_to do |format|
      if @provider.update_attributes(params[:provider])
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy

    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :create_vm %><br />
    <%= f.text_field :create_vm %>
  </div>

  <div class="field">
    <%= f.label :start_vm %><br />
    <%= f.text_field :start_vm %>
  </div>

  <div class="field">
    <%= f.label :stop_vm %><br />
    <%= f.text_field :stop_vm %>
  </div>

  <div class="field">
    <%= f.label :reboot_vm %><br />
    <%= f.text_field :reboot_vm %>
  </div>

  <div class="field">
    <%= f.label :list_vm %><br />
    <%= f.text_field :list_vm %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @providers.each do |provider| %>
  <tr>
    <td><%= provider.name %></td>
    <td><%= link_to 'Show', provider %></td>
    <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
    <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @provider.name %>
</p>

<p>
  <b>Create vm:</b>
  <%= @provider.create_vm %>
</p>

<p>
  <b>Start vm:</b>
  <%= @provider.start_vm %>
</p>

<p>
  <b>Stop vm:</b>
  <%= @provider.stop_vm %>
</p>

<p>
  <b>Reboot vm:</b>
  <%= @provider.reboot_vm %>
</p>

<p>
  <b>List vm:</b>
  <%= @provider.list_vm %>
</p>


<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>