config/routes.rb
Shurijp::Application.routes.draw do

  resources :vmresavation, only: [:new, :create, :edit, :update, :destroy]
  match 'vmresavation/:id', :to => 'vmresavation#index', :as => 'vmresavation', :via => :get

  resources :resavations, only: [:index, :show]

  get "user_property/index"

  resources :providers

  root :to => "conns#index"

  devise_for :users
  get 'conns', :to => 'conns#index', :as => :user_root

  resources :conns
  resources :vm_operations, only: [ :new, :create ] do
    member do
      get :start, :stop, :reboot
    end
  end

  match 'vm_operations/:idx', :to => 'vm_operations#index', :as => 'vm_operations', :via => :get

end

app/controllers/vm_operations_controller.rb
require 'fog'
require 'json'

class VmOperationsController < ApplicationController
  before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| 
    c.request.format == 'application/json' }
#  protect_from_forgery :except => ["create"]

  def index
    session[:idx] = params[:idx]
    session[:conn] = current_user.conns[params[:idx].to_i]

    puts "*** debug ***"
    puts session[:idx]
    puts session[:conn]
    puts current_user
    puts "*** debug ***"

    @virtual_machines = VirtualMachine.find_by_conn(current_user.conns[params[:idx].to_i])
    ret = {:virtual_machines => @virtual_machines, :authenticity => form_authenticity_token }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @virtual_machines }
#      format.json { render json: ret }
    end
  end

  def new
    puts "*** debug ***"
    puts session[:idx]
    puts session[:conn]
    puts current_user
    puts "*** debug ***"

#    new = {:authenticity => form_authenticity_token, :connid => session[:conn].id.to_s, :idx => session[:idx] }
    respond_to do |format|
      format.html # new.html.erb
#      format.json { render json: new }
    end
  end

  def create
    session[:idx] = params[:idx]
    session[:conn] = Conn.find(params[:connid])
    VirtualMachine.create_vm(session[:conn], params[:hostname])
    @virtual_machines = VirtualMachine.find_by_conn(session[:conn])
    respond_to do |format|
      format.html { redirect_to :action => 'index', :idx => session[:idx] }
      format.json { render json: @virtual_machines }
    end
  end

  def start
    VirtualMachine.start_vm(session[:conn], params[:id])
    @virtual_machines = VirtualMachine.find_by_conn(session[:conn])
    respond_to do |format|
      format.html { redirect_to :action => 'index', :idx => session[:idx] }
      format.json { render json: @virtual_machines }
    end
  end

  def stop
    VirtualMachine.stop_vm(session[:conn], params[:id])
    @virtual_machines = VirtualMachine.find_by_conn(session[:conn])
    respond_to do |format|
      format.html { redirect_to :action => 'index', :idx => session[:idx] }
      format.json { render json: @virtual_machines }
    end
  end

  def reboot
    VirtualMachine.reboot_vm(session[:conn], params[:id])
    @virtual_machines = VirtualMachine.find_by_conn(session[:conn])
    respond_to do |format|
      format.html { redirect_to :action => 'index', :idx => session[:idx] }
      format.json { render json: @virtual_machines }
    end
  end
end

app/helpers/vm_operation_helper.rb
module VmOperationHelper
end

app/views/vm_operations/create.html.erb
<h1>VmOperation#create</h1>
<p>Find me in app/views/vm_operation/create.html.erb</p>

app/views/vm_operations/index.html.erb
<h1>VmOperation#index</h1>

<table>
  <tr>
    <th>Hostname</th>
    <th>VM state</th>
    <th>start/stop</th>
  </tr>

<% @virtual_machines[:vms]["listvirtualmachinesresponse"]["virtualmachine"].each do |vm| %>
  <tr>
    <td><%= vm["displayname"] %></td>
    <td><%= vm["state"] %></td>
    <td>
      <% if vm["state"] == "Running" then %>
        <td class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operation<b class="caret"></b></a>
          <ul class="dropdown-menu">
             <li><%= link_to "Stop VM", controller:"vm_operations", action:"stop", id: vm["id"] %></li>
             <li><%= link_to "Reboot VM", controller:"vm_operations", action:"reboot", id: vm["id"] %></li>
             <li><%= link_to "Schedule", controller:"vmresavation", action:"index", id: vm["id"] %></li>
          </ul>
        </td>
      <% elsif vm["state"] == "Stopped" then %>
        <td class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operation<b class="caret"></b></a>
          <ul class="dropdown-menu">
             <li><%= link_to "Start VM", controller:"vm_operations", action:"start", id: vm["id"] %></li>
             <li><%= link_to "Schedule", controller:"vmresavation", action:"index", id: vm["id"] %></li>
          </ul>
        </td>
      
      <% else %>

      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New VM', new_vm_operation_path %>

app/views/vm_operations/new.html.erb
<h1>new VM</h1>

<%= form_tag('/vm_operations') do %>

  <%= label_tag 'Displayname' %>
  <%= text_field_tag :hostname %>

  <%= submit_tag 'deploy' %>

<% end %>

<%= link_to 'Back', :back %>

app/views/vm_operations/start.html.erb
<h1>VmOperation#start</h1>
<p>Find me in app/views/vm_operation/start.html.erb</p>

app/views/vm_operations/stop.html.erb
<h1>VmOperation#stop</h1>
<p>Find me in app/views/vm_operation/stop.html.erb</p>