config/routes.rb
Shurijp::Application.routes.draw do

  resources :vmresavation, only: [:new, :create, :edit, :update, :destroy]
  match 'vmresavation/:id', :to => 'vmresavation#index', :as => 'vmresavation', :via => :get

  resources :resavations, only: [:index, :show]

  get "user_property/index"

  resources :providers

  root :to => "conns#index"

  devise_for :users
  get 'conns', :to => 'conns#index', :as => :user_root

  resources :conns
  resources :vm_operations, only: [ :new, :create ] do
    member do
      get :start, :stop, :reboot
    end
  end

  match 'vm_operations/:idx', :to => 'vm_operations#index', :as => 'vm_operations', :via => :get

end

app/controllers/vmresavation_controller.rb
class VmresavationController < ApplicationController
  before_filter :authenticate_user!

  def index
    @resavations = Resavation.find_all_by_vmid_and_conn_id(params[:id], session[:conn].id)
#    if (@resavations == nil)
#      @resavations = []
    session[:vmid] = params[:id]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resavations }
    end
  end

  def new
    @resavation = Resavation.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resavation }
    end
  end

  def create
    @resavation = Resavation.new(params[:resavation])
    @resavation.vmid = session[:vmid]
    @resavation.conn_id = session[:conn].id
#    session[:conn].resavation = @resavation

    respond_to do |format|
      if @resavation.save
#        format.html { redirect_to @resavation, notice: 'Resavation was successfully created.' }
        format.html { redirect_to :action => "index", :id => session[:vmid] }
        format.json { render json: @resavation, status: :created, location: @resavation }
      else
        format.html { render action: "new" }
        format.json { render json: @resavation.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @resavation = Resavation.find(params[:id])
  end

  def update
    @resavation = Resavation.find(params[:id])

    respond_to do |format|
      if @resavation.update_attributes(params[:resavation])
        format.html { redirect_to :action => "index", :id => session[:vmid] }
#        format.html { redirect_to @resavation, notice: 'Resavation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resavation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resavation = Resavation.find(params[:id])
    @resavation.destroy

    respond_to do |format|
      format.html { redirect_to :action => "index", :id => session[:vmid] }
#      format.html { redirect_to resavations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vmresavation_helper.rb
module VmresavationHelper
end

app/views/vmresavation/_form.html.erb
<%= form_for @resavation, :url => {:controller => 'vmresavation'} do |f| %>
  <% if @resavation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resavation.errors.count, "error") %> prohibited this resavation from being saved:</h2>

      <ul>
      <% @resavation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operation %><br />
    <%= f.select :operation, {"Start" => "Start", "Stop" => "Stop"} %>
<!--
    <%= f.text_field :operation %>
-->
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.select :hour, {"0" => "0", "1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5", "6" => "6", "7" => "7", "8" => "8", "9" => "9", "10" => "10", "11" => "11", "12" => "12", "13" => "13", "14" => "14", "15" => "15", "16" => "16", "17" => "17", "18" => "18", "19" => "19", "20" => "20", "21" => "21", "22" => "22", "23" => "23"} %>
<!--
    <%= f.text_field :hour %>
-->
  </div>
  <div class="field">
    <%= f.label :min %><br />
    <%= f.select :min, {"00" => "00", "10" => "10", "20" => "20", "30" => "30", "40" => "40", "50" => "50"} %>
<!--
    <%= f.text_field :min %>
-->
  </div>
<!--
  <div class="field">
    <%= f.label :vmid %><br />
    <%= f.number_field :vmid %>
  </div>
  <div class="field">
    <%= f.label :conn_id %><br />
    <%= f.number_field :conn_id %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vmresavation/edit.html.erb
<h1>Vmresavation#edit</h1>

<%= form_for @resavation, :url => {:controller => 'vmresavation', :action => 'update', :id => @resavation.id} do |f| %>
  <% if @resavation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resavation.errors.count, "error") %> prohibited this resavation from being saved:</h2>

      <ul>
      <% @resavation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operation %><br />
    <%= f.select :operation, {"Start" => "Start", "Stop" => "Stop"} %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.select :hour, {"0" => "0", "1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5", "6" => "6", "7" => "7", "8" => "8", "9" => "9", "10" => "10", "11" => "11", "12" => "12", "13" => "13", "14" => "14", "15" => "15", "16" => "16", "17" => "17", "18" => "18", "19" => "19", "20" => "20", "21" => "21", "22" => "22", "23" => "23"} %>
  </div>
  <div class="field">
    <%= f.label :min %><br />
    <%= f.select :min, {"00" => "00", "10" => "10", "20" => "20", "30" => "30", "40" => "40", "50" => "50"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', {controller: "vmresavation", action: "index", id: session[:vmid]} %>

app/views/vmresavation/index.html.erb
<h1>Listing resavations</h1>

<table>
  <tr>
    <th>Operation</th>
    <th>Hour</th>
    <th>Min</th>
<!--
    <th>Vmid</th>
    <th>Conn</th>
    <th></th>
-->
    <th></th>
    <th></th>
  </tr>

<% @resavations.each do |resavation| %>
  <tr>
    <td><%= resavation.operation %></td>
    <td><%= resavation.hour %></td>
    <td><%= resavation.min %></td>
<!--
    <td><%= resavation.vmid %></td>
    <td><%= resavation.conn_id %></td>
-->
<!--
    <td><%= link_to 'Show', resavation %></td>
    <td><%= link_to 'Edit', edit_vmresavation_path(resavation) %></td>
-->
    <td><%= link_to 'Edit', edit_vmresavation_path(resavation) %></td>
    <td><%= link_to 'Destroy', "/vmresavation/" + resavation.id.to_s, :method => 'delete', :confirm => 'Are you sure?' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resavation', new_vmresavation_path %>
<%= link_to 'Back', {controller: "vm_operations", action: "index", idx: session[:idx] } %>

app/views/vmresavation/new.html.erb
<h1>New resavation</h1>

<%= form_for @resavation, :url => {:controller => 'vmresavation', :action => 'create'} do |f| %>
  <% if @resavation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resavation.errors.count, "error") %> prohibited this resavation from being saved:</h2>

      <ul>
      <% @resavation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operation %><br />
    <%= f.select :operation, {"Start" => "Start", "Stop" => "Stop"} %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.select :hour, {"0" => "0", "1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5", "6" => "6", "7" => "7", "8" => "8", "9" => "9", "10" => "10", "11" => "11", "12" => "12", "13" => "13", "14" => "14", "15" => "15", "16" => "16", "17" => "17", "18" => "18", "19" => "19", "20" => "20", "21" => "21", "22" => "22", "23" => "23"} %>
  </div>
  <div class="field">
    <%= f.label :min %><br />
    <%= f.select :min, {"00" => "00", "10" => "10", "20" => "20", "30" => "30", "40" => "40", "50" => "50"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', resavations_path %>