config/routes.rb
Shurijp::Application.routes.draw do

  resources :vmresavation, only: [:new, :create, :edit, :update, :destroy]
  match 'vmresavation/:id', :to => 'vmresavation#index', :as => 'vmresavation', :via => :get

  resources :resavations, only: [:index, :show]

  get "user_property/index"

  resources :providers

  root :to => "conns#index"

  devise_for :users
  get 'conns', :to => 'conns#index', :as => :user_root

  resources :conns
  resources :vm_operations, only: [ :new, :create ] do
    member do
      get :start, :stop, :reboot
    end
  end

  match 'vm_operations/:idx', :to => 'vm_operations#index', :as => 'vm_operations', :via => :get

end

app/models/conn.rb
class Conn < ActiveRecord::Base
  belongs_to :user
  belongs_to :provider
  has_many :virtual_machines
  has_many :resavations
  attr_accessible :access_key, :end_point, :secret_access_key, :name, :provider_id
end

app/controllers/conns_controller.rb
class ConnsController < ApplicationController
  before_filter :authenticate_user!
  # GET /conns
  # GET /conns.json
  def index
    @conns = current_user.conns

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conns }
    end
  end

  # GET /conns/1
  # GET /conns/1.json
  def show
    @conn = current_user.conns.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conn }
    end
  end

  # GET /conns/new
  # GET /conns/new.json
  def new
    @conn = current_user.conns.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conn }
    end
  end

  # GET /conns/1/edit
  def edit
    @conn = current_user.conns.find(params[:id])
  end

  # POST /conns
  # POST /conns.json
  def create
    @conn = current_user.conns.build(params[:conn])

    respond_to do |format|
      if @conn.save
        format.html { redirect_to @conn, notice: 'Conn was successfully created.' }
        format.json { render json: @conn, status: :created, location: @conn }
      else
        format.html { render action: "new" }
        format.json { render json: @conn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conns/1
  # PUT /conns/1.json
  def update
    @conn = current_user.conns.find(params[:id])

    respond_to do |format|
      if @conn.update_attributes(params[:conn])
        format.html { redirect_to @conn, notice: 'Conn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conns/1
  # DELETE /conns/1.json
  def destroy
    @conn = current_user.conns.find(params[:id])
    @conn.destroy

    respond_to do |format|
      format.html { redirect_to conns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/conns_helper.rb
module ConnsHelper
end

app/views/conns/_form.html.erb
<%= form_for(@conn) do |f| %>
  <% if @conn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conn.errors.count, "error") %> prohibited this conn from being saved:</h2>

      <ul>
      <% @conn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.collection_select :provider_id, Provider.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :access_key %><br />
    <%= f.text_field :access_key %>
  </div>
  <div class="field">
    <%= f.label :secret_access_key %><br />
    <%= f.text_field :secret_access_key %>
  </div>
  <div class="field">
    <%= f.label :end_point %><br />
    <%= f.text_field :end_point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conns/edit.html.erb
<h1>Editing conn</h1>

<%= render 'form' %>

<%= link_to 'Show', @conn %> |
<%= link_to 'Back', conns_path %>

app/views/conns/index.html.erb
<h1>Listing conns</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Provider</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conns.each_with_index do |conn, i| %>
  <tr>
    <td><%= conn.name %></td>
    <td><%= conn.provider.name %></td>
    <td class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operation<b class="caret"></b></a>
      <ul class="dropdown-menu">
         <li><%= link_to 'VMs', {:controller => 'vm_operations', :action => 'index', :idx => i} %></li>
         <li><%= link_to 'Show', conn %></li>
         <li><%= link_to 'Edit', edit_conn_path(conn) %></li>
         <li><%= link_to 'Destroy', conn, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conn', new_conn_path %>

app/views/conns/new.html.erb
<h1>New conn</h1>

<%= render 'form' %>

<%= link_to 'Back', conns_path %>

app/views/conns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @conn.name %>
</p>

<p>
  <b>Provider:</b>
  <%= @conn.provider.name %>
</p>

<p>
  <b>Access key:</b>
  <%= @conn.access_key %>
</p>

<p>
  <b>Secret access key:</b>
  <%= @conn.secret_access_key %>
</p>

<p>
  <b>End point:</b>
  <%= @conn.end_point %>
</p>


<%= link_to 'Edit', edit_conn_path(@conn) %> |
<%= link_to 'Back', conns_path %>